---
title: "Question 1"
author: "Joseph Froelicher"
date: "11/24/2020"
output: word_document
---
```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE)
```
# Part A
```{r}
A = matrix(c(3, 4, 2, 2), nrow = 2, ncol = 2, byrow = TRUE)
B = matrix(c(1, 3, 2, 4), nrow = 2, ncol = 2, byrow = TRUE)

dim(A)
dim(B)
```
A is `r dim(A)[1]` x `r dim(A)[2]`, and 
B is `r dim(B)[1]` x `r dim(B)[1]`
  
# Part B
Element $a_{12}$ is `r A[1, 2]`
  
# Part C
```{r}
A + B
```

# Part D
```{r}
A - B
```

# Part E
```{r}
A %*% B
```

# Part F
```{r}
B %*% A
```

# Part G
No, $AB \neq BA$. This is to be expected, because they are not symmetrical matrices.
  
# Part H
$A^T =$
```{r}
t(A)
```
A is not a symmetric matrix. It is only symmetric if $A = A^T$
  
# Part I
$(AB)^T =$
```{r}
t(A %*% B)
```
  
$B^TA^T =$
```{r}
t(B) %*% t(A)
```
  
Therefore, $(AB)^T=B^TA^T$
  
# Part J
```{r}
AI = solve(A)
```
$A^{-1}=$
```{r}
AI
```

# Part K
```{r}
I = matrix(c(1, 0, 0, 1), nrow = 2, ncol = 2, byrow = TRUE)
I
A %*% AI
```
