---
title: "Question 1, Homework 1"
author: "Joe Froelicher"
date: "9/10/2020"
output: word_document
fontsize: 12pt
---

## Toward Evidence-Based Medical Statistics. 1: The P Value Fallacy
# Steven N. Goodman, MD, PhD

Goodman (1999) has provided us with some insight into the different approaches to statistics,
and how we might go about reaching conclusions based upod the current schools of thought. More broadly
this is referring to the subtle but important difference between inductive and deductive reasoning
in statistics. Goodman also hints out how this may shape our thinking about one of the two common schools of
thought in statistics, frequentist statistics. For all intents and purposes, deductive reasoning implies that we assume something to be true in nature and then make a prediction about what
should happen if that were true. Alternatively, inductive reasoning in statistics allows us to first
evaluate things happening around us in nature, and then based upon that information we can make hypotheses
about the real world. 
  
The basis of statistics is its use to draw conclusions about larger populations, by doing research about
a small sample that represents that population. This implies associating from a smaller object to a much
larger object. Another important association in statistics is the ability to take observations in the
short term, and associate them to long term situations. The author argues however, that the current
mindset towards solving this problem of association is to use a P-value. Goodman makes an intriguing
argument that using a P-value to associate from the short term perspective to the long term perspective
is in fact a fallacy. The short term reasoning implies evidence based inductive conclusions, whereas the
long term reasoning implies error-based and deductive conclusions. This paradox Goodman has coined as the
P-value fallacy.  
  
As could be expected, the author does provide a (better, although admittedly  imperfect) solution to the
inductive vs. deductive paradox within the scheme of the P-value fallacy. Goodman proposes that the
commonly reported frequentist statistical approach of confidence intervals allows for a range of solution
effects that suit the data. Confidence intervals allow us to acknowldge the size of the effect at hand.
As was mentioned, this is an imperfect solution, while certainly better that P-values, confidence intervals
do not solve all of our frequentist problems (enter bayesian methods, and likelihood ratios).
